---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/ara-server
  matrix:
    - VERSION=latest
    - VERSION=1.1.0
    - VERSION=1.2.0
    - VERSION=1.3.0
    - VERSION=1.3.2
    - VERSION=1.4.0
    - VERSION=1.4.1

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
