---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/ara-server
  matrix:
    - VERSION=latest
    - VERSION=1.1.0
    - VERSION=1.2.0
    - VERSION=1.3.0
    - VERSION=1.3.2
    - VERSION=1.4.0
    - VERSION=1.4.1

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
