---
name: Build docker image

"on":
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-docker-image.yml
      - Dockerfile
      - files/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Dockerfile
      - files/**
      - scripts/*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.5.3
          - 1.5.4
          - 1.5.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: Build docker image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.version }}
          REPOSITORY: osism/ara-server

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # yamllint disable-line rule:line-length
          image-ref: '${{ secrets.DOCKER_REGISTRY }}/osism/ara-server:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push docker image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.version }}
          REPOSITORY: osism/ara-server
        if: github.ref == 'refs/heads/master'
